### PR TITLE
fix: events overhaul

### LINKED ISSUE #388: Events: Address Comments
After reviewing #263, I noticed somethings to address, feel free to thread here or in a discussion. @sunnyh2024 & @ojn03 are our domain experts (🐐 ed work from them)

- [ ] Address commented out `SeriesID` [here](https://github.com/GenerateNU/sac/pull/263/files?diff=split&w=0#diff-dce54a337a444db4d1a262e1b0ffeb5784092b5cc4dfa29d9d5edd0ed192a753R36)
- [x] Address "// TODO: add not null to required fields on all gorm models" [here](https://github.com/GenerateNU/sac/pull/263/files?diff=split&w=0#diff-dce54a337a444db4d1a262e1b0ffeb5784092b5cc4dfa29d9d5edd0ed192a753R55)
- [x] Address "// Not needed for now ..." [here](https://github.com/GenerateNU/sac/pull/263/files?diff=split&w=0#diff-dce54a337a444db4d1a262e1b0ffeb5784092b5cc4dfa29d9d5edd0ed192a753R63)
- [ ] Address "// TODO: probably need to make changes to this to update the events as well" [here](https://github.com/GenerateNU/sac/pull/263/files?diff=split&w=0#diff-dce54a337a444db4d1a262e1b0ffeb5784092b5cc4dfa29d9d5edd0ed192a753R119)

### LINKED ISSUE #668: fix: duplicate event series route
raised when regenerating the swagger docs --> `2024/04/26 19:02:49 warning: route PATCH /events/{eventID}/series/{seriesID}/ is declared multiple times`

### LINKED ISSUE #669: fix: events

### LINKED ISSUE #701: feat: private events
- [ ] You should be able to create a private or public event (private only being available to members)

### PR DESCRIPTION
**Pull request by garrettladley**
- [x] update schema
- [x] make weekly / biweekly / monthly mutually exclusive in proto

### CODE REVIEW

File: backend/entities/events/base/service.go [hunk 1]
```diff
@@ -45,53 +46,7 @@ func (e *EventService) GetEvents(limit string, page string) ([]models.Event, *er
...
-
-	// Create other events in series and update field in series (for join table)
-	events := createEventSlice(event, *series)
-	series.Events = events
-
-	return CreateEventSeries(e.DB, *series)
-}
-
-func (e *EventService) GetEvent(eventID string) ([]models.Event, *errors.Error) {
+func (e *EventService) GetEvent(eventID string) (models.Event, *errors.Error) {
```
Comment (alderwhiteford) [inline backend/entities/events/base/service.go:49]: lmao didn't realize GetEvent was returning an array before

File: backend/entities/events/base/service.go [hunk 2]
```diff
@@ -100,172 +55,45 @@ func (e *EventService) GetEvent(eventID string) ([]models.Event, *errors.Error)
...
-
-func (e *EventService) UpdateSeriesByEventID(eventID string, seriesBody models.UpdateSeriesRequestBody) ([]models.Event, *errors.Error) {
-	eventIDAsUUID, idErr := utilities.ValidateID(eventID)
-	if idErr != nil {
-		return nil, idErr
-	}
-
-	if err := e.Validate.Struct(seriesBody); err != nil {
-		return nil, &errors.FailedToValidateEventSeries
+	if body.IsSeries {
```
Comment (alderwhiteford) [inline backend/entities/events/base/service.go:68]: fuck yeah

File: backend/entities/events/base/service.go [hunk 3]
```diff
@@ -100,172 +55,45 @@ func (e *EventService) GetEvent(eventID string) ([]models.Event, *errors.Error)
...
-		EventType: eventBody.EventType,
+	events := make([]models.Event, *numOccurences)
 
-		Host:         eventBody.Host,
-		RSVP:         eventBody.RSVP,
-		Waitlist:     eventBody.Waitlist,
-		Clubs:        eventBody.Clubs,
-		Tag:          eventBody.Tag,
-		Notification: eventBody.Notification,
+	for index := 0; index < *numOccurences; index++ {
```
Comment (alderwhiteford) [inline backend/entities/events/base/service.go:93]: just curious, have you tested this?

File: backend/entities/models/event.go [hunk 4]
```diff
@@ -3,117 +3,97 @@ package models
...
+	HostID      uuid.UUID `json:"host" validate:"uuid4"`
 
+	// geoshi
+	EventType EventType `json:"event_type" validate:"required,max=255,oneof=hybrid in_person virtual"`
+	Location  string    `json:"location" validate:"max=255,required_if=EventType in_person,required_if=EventType hybrid"`
+	Link      string    `json:"link" validate:"url,max=255,required_if=EventType virtual,required_if=EventType hybrid"`
+
+	// internal housekeeping states
+	IsPublic   bool `json:"is_public" validate:"required"`
+	IsDraft    bool `json:"is_draft" validate:"required"`
```
Comment (alderwhiteford) [inline backend/entities/models/event.go:34]: MASSIVE

File: backend/protos/recurrence.go [hunk 5]
```diff
@@ -0,0 +1,190 @@
...
+// 4: [does this occur on Monday?]
+// 5: [does this occur on Tuesday?]
+// 6: [does this occur on Wednesday?]
+// 7: [does this occur on Thursday?]
+// 8: [does this occur on Friday?]
+// 9: [does this occur on Saturday?]
+// 10: [does this occur on Sunday?]
+type BinaryRecurrence []byte
+
+func (r *Recurrence) MarshallBinary() (data []byte, err error) {
```
Comment (alderwhiteford) [inline backend/protos/recurrence.go:130]: this is dope af

**Comment by alderwhiteford** [comment]
One small comment, we may want to have a const variable that we can hard set a termination date if people try to set something beyond it

File: backend/entities/events/base/service.go (hunk 3 above)
Comment (garrettladley) [reply backend/entities/events/base/service.go:93]: not yet, everything still a wip

**Review by DOOduneye — CHANGES_REQUESTED** [review]
LGTM! Amazing work with reimagining events

File: backend/config/calendar.go [hunk 6]
```diff
@@ -0,0 +1,24 @@
+package config
+
+import (
+	"time"
+)
+
+type CalendarSettings struct {
+	MaxTerminationDate time.Time
```
[the remark this answers is not in the document]
Comment (garrettladley) [reply backend/config/calendar.go:8]: since imo it is more of a config value than a constant. bumping the max termination date shouldn't require a code change, just updating the config.

[the remark this answers is not in the document]
Comment (DOOduneye) [reply backend/config/calendar.go:8]: but doesn't that mean we'd have to change it every year? it's just a date value i'm still not sure it needs to be configurable or like it makes sense with all the other configuration values we have

[the remark this answers is not in the document]
Comment (garrettladley) [reply backend/config/calendar.go:8]: how is a constant any different than what we currently have? should this be configurable by the admin dashboard? if so, how would it be stored? db?

**Comment by garrettladley** [comment]
running into issues mapping structs with fields of type time.Time to other structs with time.Time.
function [`utilities.Map`](https://github.com/GenerateNU/sac/blob/main/backend/utilities/manipulator.go#L8). Opened issue [here](https://github.com/go-viper/mapstructure/issues/20)
